name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 3.143.237.153
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # Create directory if it doesn't exist
            mkdir -p /home/ubuntu/devopos1
            
            # Navigate to the project directory
            cd /home/ubuntu/devopos1

            # Install Node.js and npm if not already installed
            if ! command -v node &> /dev/null; then
                curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
                sudo apt-get install -y nodejs
            fi

            # Install pnpm if not already installed
            if ! command -v pnpm &> /dev/null; then
                npm install -g pnpm
            fi

            # Install PM2 if not already installed
            if ! command -v pm2 &> /dev/null; then
                npm install -g pm2
            fi

            # Clone or pull the repository
            if [ ! -d ".git" ]; then
                git clone https://github.com/${{ github.repository }}.git .
            else
                git pull origin main
            fi

            # Install dependencies
            pnpm install

            # Build the application
            pnpm build

            # Start or restart the application
            if pm2 list | grep -q "devopos1"; then
                pm2 restart devopos1
            else
                pm2 start pnpm --name "devopos1" -- start
            fi

            # Save PM2 process list
            pm2 save