name: remote ssh command

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 3.149.9.165
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            whoami
            ls
            cd devopos1
            git pull
            npm install
            npm run build
            npm run dev
            

