name: remote ssh command

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 3.17.75.187
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # Navigate to project directory
            cd /home/ubuntu/devopos1
            
            # Pull latest changes
            git pull origin main
            
            # Make scripts executable
            chmod +x build.sh start.sh run.sh
            
            # Run the application
            ./run.sh

